//
// FaixaCEP.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Customer Model */
public class FaixaCEP: JSONEncodable {
    /** Nome do municipio */
    public var nome: String?
    /** inicio da faixa de CEP */
    public var inicio: String?
    /** Fim da faixa de CEP */
    public var fim: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["nome"] = self.nome
        nillableDictionary["inicio"] = self.inicio
        nillableDictionary["fim"] = self.fim
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
