//
// CEPAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class CEPAPI: APIBase {
    /**

     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter estado: (path) Abreviaçáo do Estado. 
     - parameter municipio: (query) Nome do Município. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func cepEstadoGet(clientId clientId: String, accessToken: String, estado: String, municipio: String? = nil, completion: ((data: [InlineResponse200]?, error: ErrorType?) -> Void)) {
        cepEstadoGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, estado: estado, municipio: municipio).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /cep/{estado}
     - Pesquisa pela faixa de CEPs nos municipios de um Estado.
     - examples: [{contentType=application/json, example=[ {
  "inicio" : "13000001",
  "nome" : "Campinas",
  "fim" : "13139999"
} ]}]
     
     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter estado: (path) Abreviaçáo do Estado. 
     - parameter municipio: (query) Nome do Município. (optional)

     - returns: RequestBuilder<[InlineResponse200]> 
     */
    public class func cepEstadoGetWithRequestBuilder(clientId clientId: String, accessToken: String, estado: String, municipio: String? = nil) -> RequestBuilder<[InlineResponse200]> {
        var path = "/cep/{estado}"
        path = path.stringByReplacingOccurrencesOfString("{estado}", withString: "\(estado)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "municipio": municipio
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<[InlineResponse200]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

}
