//
// EndereosAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class EndereosAPI: APIBase {
    /**

     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter cep: (path) CEP a ser pesquisado. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func enderecosCepGet(clientId clientId: String, accessToken: String, cep: String, completion: ((data: [InlineResponse2001]?, error: ErrorType?) -> Void)) {
        enderecosCepGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, cep: cep).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /enderecos/{cep}
     - Pesquisa pelo endereço de um dado CEP.
     - examples: [{contentType=application/json, example=[ {
  "uf" : "SP",
  "logradouro" : "Rua Doutor Ricardo Benetton Martins, s/n",
  "bairro" : "Polo II de Alta Tecnologia (Campinas)",
  "municipio" : "Campinas"
} ]}]
     
     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter cep: (path) CEP a ser pesquisado. 

     - returns: RequestBuilder<[InlineResponse2001]> 
     */
    public class func enderecosCepGetWithRequestBuilder(clientId clientId: String, accessToken: String, cep: String) -> RequestBuilder<[InlineResponse2001]> {
        var path = "/enderecos/{cep}"
        path = path.stringByReplacingOccurrencesOfString("{cep}", withString: "\(cep)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<[InlineResponse2001]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true, headers: headerParameters)
    }

}
