//
// ObjetoPostalAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ObjetoPostalAPI: APIBase {
    /**

     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter tipoEvento: (path) Tipo de evento a ser pesquisado. 
     - parameter statusEvento: (query) Status a ser filtrado. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func eventosTipoEventoGet(clientId clientId: String, accessToken: String, tipoEvento: String, statusEvento: String? = nil, completion: ((data: [InlineResponse2003]?, error: ErrorType?) -> Void)) {
        eventosTipoEventoGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, tipoEvento: tipoEvento, statusEvento: statusEvento).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /eventos/{tipoEvento}
     - Retorna uma lista de possiveis status para um determinado evento.
     - examples: [{contentType=application/json, example=[ {
  "statusEvento" : 1,
  "tipoEvento" : "BDE",
  "descricaoEvento" : "Entregue"
} ]}]
     
     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter tipoEvento: (path) Tipo de evento a ser pesquisado. 
     - parameter statusEvento: (query) Status a ser filtrado. (optional)

     - returns: RequestBuilder<[InlineResponse2003]> 
     */
    public class func eventosTipoEventoGetWithRequestBuilder(clientId clientId: String, accessToken: String, tipoEvento: String, statusEvento: String? = nil) -> RequestBuilder<[InlineResponse2003]> {
        var path = "/eventos/{tipoEvento}"
        path = path.stringByReplacingOccurrencesOfString("{tipoEvento}", withString: "\(tipoEvento)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "statusEvento": statusEvento
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<[InlineResponse2003]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter codigoObjeto: (path) Codigo do objeto a ser pesquisado. 
     - parameter tipoEvento: (query) Tipo de evento a ser filtrado. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func objetosCodigoObjetoGet(clientId clientId: String, accessToken: String, codigoObjeto: String, tipoEvento: String? = nil, completion: ((data: [ObjetosEventos]?, error: ErrorType?) -> Void)) {
        objetosCodigoObjetoGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, codigoObjeto: codigoObjeto, tipoEvento: tipoEvento).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /objetos/{codigoObjeto}
     - Pesquisa por informações relacionadas a um objeto postal especifico.
     - examples: [{contentType=application/json, example=[ {
  "statusEvento" : 1,
  "nomeUnidade" : "CEE PAMPULHA",
  "codigoSRO" : "31277971",
  "codigoDR" : "",
  "siglaDR" : "",
  "municipio" : "BELO HORIZONTE",
  "numeroLista" : "",
  "entregador" : "",
  "uf" : "MG",
  "codigoObjeto" : "PL177497655BR",
  "codigoMCU" : "",
  "estacao" : "",
  "tipoEvento" : "OEC",
  "dataGravacao" : "",
  "usuario" : "",
  "acaoBloqueio" : "",
  "descricaoEvento" : "Saiu para entrega ao destinatário",
  "dataCriacao" : "11/05/2017 12:16:54"
} ]}]
     
     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter codigoObjeto: (path) Codigo do objeto a ser pesquisado. 
     - parameter tipoEvento: (query) Tipo de evento a ser filtrado. (optional)

     - returns: RequestBuilder<[ObjetosEventos]> 
     */
    public class func objetosCodigoObjetoGetWithRequestBuilder(clientId clientId: String, accessToken: String, codigoObjeto: String, tipoEvento: String? = nil) -> RequestBuilder<[ObjetosEventos]> {
        var path = "/objetos/{codigoObjeto}"
        path = path.stringByReplacingOccurrencesOfString("{codigoObjeto}", withString: "\(codigoObjeto)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "tipoEvento": tipoEvento
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<[ObjetosEventos]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

    /**

     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter codigoObjeto: (query) Lista, separada por virgula, com codigos de objetos postais. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func objetosGet(clientId clientId: String, accessToken: String, codigoObjeto: String, completion: ((data: [InlineResponse2002]?, error: ErrorType?) -> Void)) {
        objetosGetWithRequestBuilder(clientId: clientId, accessToken: accessToken, codigoObjeto: codigoObjeto).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     - GET /objetos
     - Pesquisa por informações relacionados a uma lista de objetos postais.
     - examples: [{contentType=application/json, example=[ {
  "numero" : "PL177497655BR",
  "eventos" : [ {
    "statusEvento" : 1,
    "nomeUnidade" : "CEE PAMPULHA",
    "codigoSRO" : "31277971",
    "codigoDR" : "",
    "siglaDR" : "",
    "municipio" : "BELO HORIZONTE",
    "numeroLista" : "",
    "entregador" : "",
    "uf" : "MG",
    "codigoObjeto" : "PL177497655BR",
    "codigoMCU" : "",
    "estacao" : "",
    "tipoEvento" : "OEC",
    "dataGravacao" : "",
    "usuario" : "",
    "acaoBloqueio" : "",
    "descricaoEvento" : "Saiu para entrega ao destinatário",
    "dataCriacao" : "11/05/2017 12:16:54"
  } ]
} ]}]
     
     - parameter clientId: (header) Identificaçáo do cliente usado na autenticaçáo. 
     - parameter accessToken: (header) Access token usado na autenticaçáo. 
     - parameter codigoObjeto: (query) Lista, separada por virgula, com codigos de objetos postais. 

     - returns: RequestBuilder<[InlineResponse2002]> 
     */
    public class func objetosGetWithRequestBuilder(clientId clientId: String, accessToken: String, codigoObjeto: String) -> RequestBuilder<[InlineResponse2002]> {
        let path = "/objetos"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "codigoObjeto": codigoObjeto
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
        let nillableHeaders: [String: AnyObject?] = [
            "client_id": clientId,
            "access_token": accessToken
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)
 
        let requestBuilder: RequestBuilder<[InlineResponse2002]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false, headers: headerParameters)
    }

}
